# Generated by Django 4.1.7 on 2023-06-02 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_userdetails_userdetail'),
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='project',
        ),
        migrations.AlterField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='users.manager'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('W', 'Working'), ('P', 'Pending'), ('C', 'Completed')], default='W', max_length=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('W', 'Working'), ('P', 'Pending'), ('C', 'Completed')], default='W', max_length=1),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('W', 'Working'), ('P', 'Pending'), ('C', 'Completed')], default='W', max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='projectteammember',
            unique_together={('employee', 'project')},
        ),
    ]
